services:
  rclone-longnamefs:
    image: ghcr.io/dangh/vfs-layer:latest
    pull_policy: always
    privileged: true
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    volumes:
      - /mnt/user/vfs/storage:/storage
      - /mnt/user/vfs/view:/view:rshared
      - /mnt/user/vfs/config:/config
    restart: unless-stopped
